In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

In [2]:
df1 = pd.read_excel("C:/Users/User10/PycharmProjects/BPSversion1/skin/dataset/data64.xlsx")
df2 = pd.read_csv("C:/Users/User10/PycharmProjects/BPSversion1/skin/dataset/resultdata64.csv")

In [3]:
df1

,ID,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,...,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64
0,1,-0.047250,0.021914,-0.479502,-0.188971,0.006633,-0.016047,-0.002986,-0.329514,0.375469,...,-0.099951,0.011121,0.006535,-0.011163,-0.020783,-0.041831,-0.020144,-0.011491,-0.301879,-0.030549
1,2,-0.052601,-0.016568,-0.175990,-0.153471,0.007068,-0.018521,0.000176,-0.157408,0.116759,...,-0.111767,0.009484,0.005082,-0.009624,-0.022003,-0.041819,-0.175267,-0.011735,-0.291649,-0.034183
2,3,-0.259217,0.046521,0.950983,-0.003660,0.006138,-0.016047,-0.039728,-0.407930,-0.757937,...,-0.108811,0.007258,-0.021684,-0.006817,-0.008609,-0.047636,-0.270637,0.002269,-0.549296,-0.037978
3,4,0.088328,0.017722,-0.540323,-0.194584,0.007411,0.025332,0.028561,-0.326402,-0.366550,...,-0.130015,0.009634,0.021932,-0.009791,-0.023085,0.076183,0.033484,-0.017165,0.187840,0.000147
4,5,0.011902,0.123401,0.730972,0.081123,0.008173,-0.000894,0.011519,-0.579511,-0.332887,...,0.282996,0.010097,0.067074,-0.010255,0.145350,-0.039437,-0.273849,-0.015402,-0.050778,-0.036754
5,6,-0.010750,0.086701,-0.346591,-0.181137,-0.003539,-0.016047,0.006358,-0.503997,5.041410,...,-0.070354,0.009262,0.018873,-0.009347,-0.019308,-0.012435,0.101262,-0.018343,0.466657,0.106426
6,7,0.111888,-0.062905,-0.142794,-0.097832,0.007441,0.003512,0.032656,0.209754,-0.274358,...,2.406668,0.010832,0.015647,-0.010989,-0.019918,-0.025502,-0.044978,-0.017065,0.170080,-0.040464
7,8,0.088218,-0.046319,-0.100240,-0.134195,0.007406,0.067292,0.020495,0.047434,0.278520,...,-0.109888,0.009933,0.015024,-0.010169,-0.022562,-0.035791,-0.168522,-0.014520,-0.129571,-0.034311
8,9,0.062672,0.015089,1.097010,-0.037911,0.007220,0.034639,0.023357,-0.304130,-0.349853,...,0.194695,0.009868,0.018023,-0.010026,-0.021056,-0.044290,-0.087922,-0.014573,-0.125302,0.147623
9,10,-0.054596,-0.000543,-0.604758,-0.201822,0.006674,0.003128,-0.002917,-0.249745,-0.381272,...,-0.152830,0.009420,0.005289,-0.009577,-0.020934,-0.040833,-0.185737,-0.008312,-0.402327,-0.039541
10,11,-0.590725,-0.084276,0.011862,-0.093685,0.007753,-0.103490,-0.089049,0.326210,-0.578401,...,-0.091529,0.005715,-0.035137,-0.005873,-0.023317,-0.028443,-0.281292,-0.012731,-0.244530,-0.041845

In [4]:
df2

    Unnamed: 0     0     1
0            0  0.42  0.58
1            1  0.92  0.08
2            2  0.68  0.32
3            3  1.00  0.00
4            4  0.98  0.02
5            5  0.78  0.22
6            6  1.00  0.00
7            7  1.00  0.00
8            8  1.00  0.00
9            9  1.00  0.00
10          10  0.97  0.03

In [5]:
df2.rename( columns={'Unnamed: 0':'ResultIndex'}, inplace=True )

In [6]:
df2

    ResultIndex     0     1
0             0  0.42  0.58
1             1  0.92  0.08
2             2  0.68  0.32
3             3  1.00  0.00
4             4  0.98  0.02
5             5  0.78  0.22
6             6  1.00  0.00
7             7  1.00  0.00
8             8  1.00  0.00
9             9  1.00  0.00
10           10  0.97  0.03

In [7]:
df3 = pd.merge(df1, df2, right_index=True, left_index = True)

In [8]:
df3

,ID,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,...,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,ResultIndex,0,1
0,1,-0.047250,0.021914,-0.479502,-0.188971,0.006633,-0.016047,-0.002986,-0.329514,0.375469,...,-0.011163,-0.020783,-0.041831,-0.020144,-0.011491,-0.301879,-0.030549,0,0.42,0.58
1,2,-0.052601,-0.016568,-0.175990,-0.153471,0.007068,-0.018521,0.000176,-0.157408,0.116759,...,-0.009624,-0.022003,-0.041819,-0.175267,-0.011735,-0.291649,-0.034183,1,0.92,0.08
2,3,-0.259217,0.046521,0.950983,-0.003660,0.006138,-0.016047,-0.039728,-0.407930,-0.757937,...,-0.006817,-0.008609,-0.047636,-0.270637,0.002269,-0.549296,-0.037978,2,0.68,0.32
3,4,0.088328,0.017722,-0.540323,-0.194584,0.007411,0.025332,0.028561,-0.326402,-0.366550,...,-0.009791,-0.023085,0.076183,0.033484,-0.017165,0.187840,0.000147,3,1.00,0.00
4,5,0.011902,0.123401,0.730972,0.081123,0.008173,-0.000894,0.011519,-0.579511,-0.332887,...,-0.010255,0.145350,-0.039437,-0.273849,-0.015402,-0.050778,-0.036754,4,0.98,0.02
5,6,-0.010750,0.086701,-0.346591,-0.181137,-0.003539,-0.016047,0.006358,-0.503997,5.041410,...,-0.009347,-0.019308,-0.012435,0.101262,-0.018343,0.466657,0.106426,5,0.78,0.22
6,7,0.111888,-0.062905,-0.142794,-0.097832,0.007441,0.003512,0.032656,0.209754,-0.274358,...,-0.010989,-0.019918,-0.025502,-0.044978,-0.017065,0.170080,-0.040464,6,1.00,0.00
7,8,0.088218,-0.046319,-0.100240,-0.134195,0.007406,0.067292,0.020495,0.047434,0.278520,...,-0.010169,-0.022562,-0.035791,-0.168522,-0.014520,-0.129571,-0.034311,7,1.00,0.00
8,9,0.062672,0.015089,1.097010,-0.037911,0.007220,0.034639,0.023357,-0.304130,-0.349853,...,-0.010026,-0.021056,-0.044290,-0.087922,-0.014573,-0.125302,0.147623,8,1.00,0.00
9,10,-0.054596,-0.000543,-0.604758,-0.201822,0.006674,0.003128,-0.002917,-0.249745,-0.381272,...,-0.009577,-0.020934,-0.040833,-0.185737,-0.008312,-0.402327,-0.039541,9,1.00,0.00
10,11,-0.590725,-0.084276,0.011862,-0.093685,0.007753,-0.103490,-0.089049,0.326210,-0.578401,...,-0.005873,-0.023317,-0.028443,-0.281292,-0.012731,-0.244530,-0.041845,10,0.97,0.03