In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

In [2]:
df64 = pd.read_csv("C:/Users/User10/Desktop/fyp/dataset/bankruptcyTrain.csv")

In [3]:
df64.head()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,target
0,-0.031545,-0.091313,-0.040269,-0.013529,0.007406,-0.016047,-0.000264,0.641242,-0.748385,0.126789,...,0.014367,0.005457,-0.014143,-0.020924,0.068399,-0.214478,-0.013915,-0.173939,-0.046788,0
1,-0.231729,-0.049448,0.304381,-0.080975,0.007515,-0.016047,-0.034963,0.074710,0.469815,0.073759,...,0.008492,-0.008385,-0.008666,-0.023095,-0.033498,-0.205796,-0.015174,-0.073056,-0.027236,0
2,-0.058602,0.065060,-0.488404,-0.189489,0.006572,-0.016047,-0.004954,-0.456287,0.270351,-0.071287,...,0.010819,0.006779,-0.009437,-0.007919,-0.043455,0.019740,-0.011736,-0.291624,-0.033580,0
3,-0.069376,0.044641,-0.181684,-0.140032,0.007477,-0.010915,-0.005599,-0.462971,-0.286746,-0.085266,...,0.010683,0.005384,-0.010840,0.001381,-0.042828,-0.350519,0.002969,-0.554685,-0.046823,0
4,0.236424,-0.051912,0.678337,-0.014680,0.007879,-0.016047,0.057418,0.097183,0.423405,0.076880,...,0.010970,0.025295,-0.011056,-0.022535,-0.035892,-0.181557,-0.015623,-0.027841,-0.023694,0

In [9]:
df54 = df64[['Attr2', 'Attr4', 'Attr5', 'Attr6', 'Attr8', 'Attr9', 'Attr10',
       'Attr11', 'Attr12', 'Attr13', 'Attr14', 'Attr15', 'Attr16', 'Attr17',
       'Attr18', 'Attr19', 'Attr20', 'Attr23', 'Attr24', 'Attr25', 'Attr26',
       'Attr27', 'Attr28', 'Attr29', 'Attr30', 'Attr32', 'Attr34', 'Attr35',
       'Attr36', 'Attr37', 'Attr38', 'Attr39', 'Attr40', 'Attr41', 'Attr42',
       'Attr44', 'Attr45', 'Attr46', 'Attr48', 'Attr49', 'Attr50', 'Attr51',
       'Attr52', 'Attr53', 'Attr54', 'Attr55', 'Attr56', 'Attr57', 'Attr58',
       'Attr59', 'Attr60', 'Attr61', 'Attr62', 'Attr63','target']]

In [10]:
df54.head()

,Attr2,Attr4,Attr5,Attr6,Attr8,Attr9,Attr10,Attr11,Attr12,Attr13,...,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,target
0,-0.091313,-0.013529,0.007406,-0.016047,0.641242,-0.748385,0.126789,-0.214423,-0.036576,-0.010930,...,-0.110578,0.014367,0.005457,-0.014143,-0.020924,0.068399,-0.214478,-0.013915,-0.173939,0
1,-0.049448,-0.080975,0.007515,-0.016047,0.074710,0.469815,0.073759,-0.835505,-0.299606,-0.013057,...,-0.114919,0.008492,-0.008385,-0.008666,-0.023095,-0.033498,-0.205796,-0.015174,-0.073056,0
2,0.065060,-0.189489,0.006572,-0.016047,-0.456287,0.270351,-0.071287,0.156944,-0.151208,-0.011717,...,-0.123266,0.010819,0.006779,-0.009437,-0.007919,-0.043455,0.019740,-0.011736,-0.291624,0
3,0.044641,-0.140032,0.007477,-0.010915,-0.462971,-0.286746,-0.085266,-0.314756,-0.145529,-0.011006,...,-0.077078,0.010683,0.005384,-0.010840,0.001381,-0.042828,-0.350519,0.002969,-0.554685,0
4,-0.051912,-0.014680,0.007879,-0.016047,0.097183,0.423405,0.076880,0.918860,0.208686,-0.008905,...,-0.076644,0.010970,0.025295,-0.011056,-0.022535,-0.035892,-0.181557,-0.015623,-0.027841,0

In [11]:
df41 = df64[['Attr2', 'Attr5', 'Attr6', 'Attr8', 'Attr9', 'Attr12', 'Attr13',
       'Attr15', 'Attr16', 'Attr17', 'Attr20', 'Attr23', 'Attr24', 'Attr25',
       'Attr26', 'Attr27', 'Attr29', 'Attr30', 'Attr32', 'Attr34', 'Attr35',
       'Attr37', 'Attr38', 'Attr39', 'Attr41', 'Attr42', 'Attr45', 'Attr46',
       'Attr48', 'Attr49', 'Attr50', 'Attr53', 'Attr54', 'Attr55', 'Attr56',
       'Attr57', 'Attr58', 'Attr59', 'Attr61', 'Attr62', 'Attr63','target']]

In [12]:
df41.head()

,Attr2,Attr5,Attr6,Attr8,Attr9,Attr12,Attr13,Attr15,Attr16,Attr17,...,Attr54,Attr55,Attr56,Attr57,Attr58,Attr59,Attr61,Attr62,Attr63,target
0,-0.091313,0.007406,-0.016047,0.641242,-0.748385,-0.036576,-0.010930,-0.005305,-0.242796,0.579994,...,-0.018113,-0.110578,0.014367,0.005457,-0.014143,-0.020924,-0.214478,-0.013915,-0.173939,0
1,-0.049448,0.007515,-0.016047,0.074710,0.469815,-0.299606,-0.013057,-0.119627,-0.603332,0.040666,...,-0.014462,-0.114919,0.008492,-0.008385,-0.008666,-0.023095,-0.205796,-0.015174,-0.073056,0
2,0.065060,0.006572,-0.016047,-0.456287,0.270351,-0.151208,-0.011717,0.009484,-0.367159,-0.464823,...,-0.019637,-0.123266,0.010819,0.006779,-0.009437,-0.007919,0.019740,-0.011736,-0.291624,0
3,0.044641,0.007477,-0.010915,-0.462971,-0.286746,-0.145529,-0.011006,0.045912,-0.454498,-0.413685,...,-0.019978,-0.077078,0.010683,0.005384,-0.010840,0.001381,-0.350519,0.002969,-0.554685,0
4,-0.051912,0.007879,-0.016047,0.097183,0.423405,0.208686,-0.008905,-0.021015,0.744187,0.062059,...,-0.010739,-0.076644,0.010970,0.025295,-0.011056,-0.022535,-0.181557,-0.015623,-0.027841,0

In [13]:
df36 = df64[['Attr2', 'Attr5', 'Attr6', 'Attr9', 'Attr12', 'Attr13', 'Attr15',
       'Attr16', 'Attr17', 'Attr20', 'Attr23', 'Attr24', 'Attr25', 'Attr26',
       'Attr27', 'Attr29', 'Attr30', 'Attr32', 'Attr34', 'Attr35', 'Attr37',
       'Attr39', 'Attr41', 'Attr42', 'Attr45', 'Attr46', 'Attr48', 'Attr49',
       'Attr50', 'Attr53', 'Attr55', 'Attr57', 'Attr58', 'Attr59', 'Attr61',
       'Attr62','target']]

In [14]:
df36.head()

,Attr2,Attr5,Attr6,Attr9,Attr12,Attr13,Attr15,Attr16,Attr17,Attr20,...,Attr49,Attr50,Attr53,Attr55,Attr57,Attr58,Attr59,Attr61,Attr62,target
0,-0.091313,0.007406,-0.016047,-0.748385,-0.036576,-0.010930,-0.005305,-0.242796,0.579994,-0.070344,...,0.004856,-0.192331,-0.016363,-0.110578,0.005457,-0.014143,-0.020924,-0.214478,-0.013915,0
1,-0.049448,0.007515,-0.016047,0.469815,-0.299606,-0.013057,-0.119627,-0.603332,0.040666,-0.047947,...,-0.025223,0.186782,-0.003012,-0.114919,-0.008385,-0.008666,-0.023095,-0.205796,-0.015174,0
2,0.065060,0.006572,-0.016047,0.270351,-0.151208,-0.011717,0.009484,-0.367159,-0.464823,0.001761,...,0.030258,-0.468628,-0.030162,-0.123266,0.006779,-0.009437,-0.007919,0.019740,-0.011736,0
3,0.044641,0.007477,-0.010915,-0.286746,-0.145529,-0.011006,0.045912,-0.454498,-0.413685,-0.006430,...,0.058513,-0.515188,-0.033926,-0.077078,0.005384,-0.010840,0.001381,-0.350519,0.002969,0
4,-0.051912,0.007879,-0.016047,0.423405,0.208686,-0.008905,-0.021015,0.744187,0.062059,-0.043107,...,0.063054,0.342874,0.005230,-0.076644,0.025295,-0.011056,-0.022535,-0.181557,-0.015623,0

In [15]:
df13 = df64[['Attr5', 'Attr6', 'Attr9', 'Attr13', 'Attr16', 'Attr25', 'Attr26',
       'Attr27', 'Attr29', 'Attr34', 'Attr39', 'Attr46', 'Attr58','target']]

In [16]:
df13.head()

,Attr5,Attr6,Attr9,Attr13,Attr16,Attr25,Attr26,Attr27,Attr29,Attr34,Attr39,Attr46,Attr58,target
0,0.007406,-0.016047,-0.748385,-0.010930,-0.242796,0.050225,-0.206675,-0.009990,-0.631107,-0.144382,-0.016173,0.147450,-0.014143,0
1,0.007515,-0.016047,0.469815,-0.013057,-0.603332,0.274101,-0.591456,-0.010933,-1.168550,1.228971,-0.052642,-0.013532,-0.008666,0
2,0.006572,-0.016047,0.270351,-0.011717,-0.367159,-0.114349,-0.339401,-0.009932,0.096212,0.059970,0.068469,-0.234744,-0.009437,0
3,0.007477,-0.010915,-0.286746,-0.011006,-0.454498,-0.105949,-0.442992,-0.009921,0.296277,-0.643082,0.071021,-0.067912,-0.010840,0
4,0.007879,-0.016047,0.423405,-0.008905,0.744187,-0.127631,0.675202,-0.009057,-0.501471,0.891985,0.076296,0.049879,-0.011056,0

In [20]:
labels64 = df64.columns[0:64]
x64 = df64[labels64]
y64 = df64['target']

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

In [23]:
x_train64, x_test64, y_train64, y_test64 = train_test_split(x64,y64, test_size = 0.2, random_state = 0)

print("Number transactions X_train64 dataset: ", x_train64.shape)
print("Number transactions y_train64 dataset: ", y_train64.shape)
print("Number transactions X_test64 dataset: ", x_test64.shape)
print("Number transactions y_test64 dataset: ", y_test64.shape)

Number transactions X_train64 dataset:  (8000, 64)
Number transactions y_train64 dataset:  (8000,)
Number transactions X_test64 dataset:  (2000, 64)
Number transactions y_test64 dataset:  (2000,)

In [25]:
from imblearn.over_sampling import SMOTE

print("Before OverSampling, counts of label '1': {}".format(sum(y_train64==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train64==0)))

sm = SMOTE(random_state=2)
x_train64_res, y_train64_res = sm.fit_sample(x_train64, y_train64.ravel())

print('After OverSampling, the shape of train_X64: {}'.format(x_train64_res.shape))
print('After OverSampling, the shape of train_y64: {} \n'.format(y_train64_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train64_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train64_res==0)))

Before OverSampling, counts of label '1': 151
Before OverSampling, counts of label '0': 7849

After OverSampling, the shape of train_X64: (15698, 64)
After OverSampling, the shape of train_y64: (15698,)

After OverSampling, counts of label '1': 7849
After OverSampling, counts of label '0': 7849

In [26]:
model64 = RandomForestClassifier(n_estimators= 100)
model64.fit(x_train64_res, y_train64_res)

RandomForestClassifier()

In [27]:
test_accuracy64 = model64.score(x_test64,y_test64)
print("Accuracy: %.2f%%" % (test_accuracy64 * 100.0))

Accuracy: 96.50%

In [28]:
y_pred64 = model64.predict(x_test64)

accuracy64 = accuracy_score(y_test64, y_pred64)
print("Accuracy: %.2f%%" % (accuracy64 * 100.0))

Accuracy: 96.50%

In [29]:
from joblib import dump, load
dump(model64,'BPSRFmodel64.joblib')

['BPSRFmodel64.joblib']

In [30]:
labels54 = df54.columns[0:54]
x54 = df54[labels54]
y54 = df54['target']

x_train54, x_test54, y_train54, y_test54 = train_test_split(x54,y54, test_size = 0.2, random_state = 0)

print("Number transactions X_train54 dataset: ", x_train54.shape)
print("Number transactions y_train54 dataset: ", y_train54.shape)
print("Number transactions X_test54 dataset: ", x_test54.shape)
print("Number transactions y_test54 dataset: ", y_test54.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train54==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train54==0)))

sm = SMOTE(random_state=2)
x_train54_res, y_train54_res = sm.fit_sample(x_train54, y_train54.ravel())

print('After OverSampling, the shape of train_X54: {}'.format(x_train54_res.shape))
print('After OverSampling, the shape of train_y54: {} \n'.format(y_train54_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train54_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train54_res==0)))

model54 = RandomForestClassifier(n_estimators= 100)
model54.fit(x_train54_res, y_train54_res)

test_accuracy54 = model54.score(x_test54,y_test54)
print("Accuracy: %.2f%%" % (test_accuracy54 * 100.0))

y_pred54 = model54.predict(x_test54)

accuracy54 = accuracy_score(y_test54, y_pred54)
print("Accuracy: %.2f%%" % (accuracy54 * 100.0))

Number transactions X_train54 dataset:  (8000, 54)
Number transactions y_train54 dataset:  (8000,)
Number transactions X_test54 dataset:  (2000, 54)
Number transactions y_test54 dataset:  (2000,)
Before OverSampling, counts of label '1': 151
Before OverSampling, counts of label '0': 7849

After OverSampling, the shape of train_X54: (15698, 54)
After OverSampling, the shape of train_y54: (15698,)

After OverSampling, counts of label '1': 7849
After OverSampling, counts of label '0': 7849
Accuracy: 96.20%
Accuracy: 96.20%

In [31]:
dump(model54,'BPSRFmodel54.joblib')

['BPSRFmodel54.joblib']

In [32]:
labels41 = df41.columns[0:41]
x41 = df41[labels41]
y41 = df41['target']

x_train41, x_test41, y_train41, y_test41 = train_test_split(x41,y41, test_size = 0.2, random_state = 0)

print("Number transactions X_train41 dataset: ", x_train41.shape)
print("Number transactions y_train41 dataset: ", y_train41.shape)
print("Number transactions X_test41 dataset: ", x_test41.shape)
print("Number transactions y_test41 dataset: ", y_test41.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train41==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train41==0)))

sm = SMOTE(random_state=2)
x_train41_res, y_train41_res = sm.fit_sample(x_train41, y_train41.ravel())

print('After OverSampling, the shape of train_X41: {}'.format(x_train41_res.shape))
print('After OverSampling, the shape of train_y41: {} \n'.format(y_train41_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train41_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train41_res==0)))

model41 = RandomForestClassifier(n_estimators= 100)
model41.fit(x_train41_res, y_train41_res)

test_accuracy41 = model41.score(x_test41,y_test41)
print("Accuracy: %.2f%%" % (test_accuracy41 * 100.0))

y_pred41 = model41.predict(x_test41)

accuracy41 = accuracy_score(y_test41, y_pred41)
print("Accuracy: %.2f%%" % (accuracy41 * 100.0))

Number transactions X_train41 dataset:  (8000, 41)
Number transactions y_train41 dataset:  (8000,)
Number transactions X_test41 dataset:  (2000, 41)
Number transactions y_test41 dataset:  (2000,)
Before OverSampling, counts of label '1': 151
Before OverSampling, counts of label '0': 7849

After OverSampling, the shape of train_X41: (15698, 41)
After OverSampling, the shape of train_y41: (15698,)

After OverSampling, counts of label '1': 7849
After OverSampling, counts of label '0': 7849
Accuracy: 96.40%
Accuracy: 96.40%

In [33]:
dump(model41,'BPSRFmodel41.joblib')

['BPSRFmodel41.joblib']

In [35]:
labels36 = df36.columns[0:36]
x36 = df36[labels36]
y36 = df36['target']

x_train36, x_test36, y_train36, y_test36 = train_test_split(x36,y36, test_size = 0.2, random_state = 0)

print("Number transactions X_train36 dataset: ", x_train36.shape)
print("Number transactions y_train36 dataset: ", y_train36.shape)
print("Number transactions X_test36 dataset: ", x_test36.shape)
print("Number transactions y_test36 dataset: ", y_test36.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train36==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train36==0)))

sm = SMOTE(random_state=2)
x_train36_res, y_train36_res = sm.fit_sample(x_train36, y_train36.ravel())

print('After OverSampling, the shape of train_X36: {}'.format(x_train36_res.shape))
print('After OverSampling, the shape of train_y36: {} \n'.format(y_train36_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train36_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train36_res==0)))

model36 = RandomForestClassifier(n_estimators= 100)
model36.fit(x_train36_res, y_train36_res)

test_accuracy36 = model36.score(x_test36,y_test36)
print("Accuracy: %.2f%%" % (test_accuracy36 * 100.0))

y_pred36 = model36.predict(x_test36)

accuracy36 = accuracy_score(y_test36, y_pred36)
print("Accuracy: %.2f%%" % (accuracy36 * 100.0))

Number transactions X_train36 dataset:  (8000, 36)
Number transactions y_train36 dataset:  (8000,)
Number transactions X_test36 dataset:  (2000, 36)
Number transactions y_test36 dataset:  (2000,)
Before OverSampling, counts of label '1': 151
Before OverSampling, counts of label '0': 7849

After OverSampling, the shape of train_X36: (15698, 36)
After OverSampling, the shape of train_y36: (15698,)

After OverSampling, counts of label '1': 7849
After OverSampling, counts of label '0': 7849
Accuracy: 96.35%
Accuracy: 96.35%

In [36]:
dump(model36,'BPSRFmodel36.joblib')

['BPSRFmodel36.joblib']

In [37]:
labels13 = df13.columns[0:13]
x13 = df13[labels13]
y13 = df13['target']

x_train13, x_test13, y_train13, y_test13 = train_test_split(x13,y13, test_size = 0.2, random_state = 0)

print("Number transactions X_train13 dataset: ", x_train13.shape)
print("Number transactions y_train13 dataset: ", y_train13.shape)
print("Number transactions X_test13 dataset: ", x_test13.shape)
print("Number transactions y_test13 dataset: ", y_test13.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train13==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train13==0)))

sm = SMOTE(random_state=2)
x_train13_res, y_train13_res = sm.fit_sample(x_train13, y_train13.ravel())

print('After OverSampling, the shape of train_X36: {}'.format(x_train13_res.shape))
print('After OverSampling, the shape of train_y36: {} \n'.format(y_train13_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train13_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train13_res==0)))

model13 = RandomForestClassifier(n_estimators= 100)
model13.fit(x_train13_res, y_train13_res)

test_accuracy13 = model13.score(x_test13,y_test13)
print("Accuracy: %.2f%%" % (test_accuracy13 * 100.0))

y_pred13 = model13.predict(x_test13)

accuracy13 = accuracy_score(y_test13, y_pred13)
print("Accuracy: %.2f%%" % (accuracy13 * 100.0))

Number transactions X_train13 dataset:  (8000, 13)
Number transactions y_train13 dataset:  (8000,)
Number transactions X_test13 dataset:  (2000, 13)
Number transactions y_test13 dataset:  (2000,)
Before OverSampling, counts of label '1': 151
Before OverSampling, counts of label '0': 7849

After OverSampling, the shape of train_X36: (15698, 13)
After OverSampling, the shape of train_y36: (15698,)

After OverSampling, counts of label '1': 7849
After OverSampling, counts of label '0': 7849
Accuracy: 95.55%
Accuracy: 95.55%

In [38]:
dump(model13,'BPSRFmodel13.joblib')

['BPSRFmodel13.joblib']